[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["extra"]

[dist.dependencies.apt]
build-essential = { stage = ["build", "run"] }
libpam-dev = { stage = ["build", "run"] }
